"""Typed diagnostic model exports."""

from .analysis_result import (
    AnalysisProfile,
    AnalysisResult,
    AnalysisSettingsSnapshot,
    AnalysisSeverity,
    BuildVolumeFitState,
    BuildVolumeMetrics,
    CheckConfidence,
    CheckResult,
    CheckTiming,
    ContainmentEvidence,
    DeepDiagnosticMetrics,
    DimensionMetrics,
    EdgeManifoldState,
    EvaluationStatus,
    GeometryMetrics,
    IssueCategory,
    IssueDomain,
    IssueEvidence,
    NormalConsistencyState,
    ObjectMetadata,
    PrinterProfile,
    SelfIntersectionState,
    ShellContainmentState,
    ShellMetrics,
    ShellOrientationState,
    SurfaceVolumeMetrics,
    TopologyMetrics,
    TopologySignature,
    TransformMetrics,
    VertexManifoldState,
    WatertightState,
)
from .repair_models import (
    RepairAudit,
    RepairCandidate,
    RepairCandidateType,
    RepairCheckpointRecord,
    RepairComparison,
    RepairConfidence,
    RepairDecision,
    RepairOperationRecord,
    RepairOperationStatus,
    RepairOperationType,
    RepairPlan,
    RepairPlanItem,
    RepairPlanStatus,
    RepairSession,
    RepairSessionStatus,
    RepairSettingsSnapshot,
)
from .printability_models import (
    BuildPlateContactResult,
    ContactClassification,
    EvidenceState,
    FloatingComponentResult,
    GeometryFacts as PrintabilityGeometryFacts,
    OrientationCandidate,
    OrientationResult,
    PrintabilityConfidence,
    PrintabilityMode,
    PrintabilityReport,
    PrintabilityResult,
    PrintabilityRiskItem,
    PrintabilityScore,
    PrintabilitySettingsSnapshot,
    PrintabilityStatus,
    PrinterProfile as PrintabilityPrinterProfile,
    PrinterProfileSnapshot,
    ProcessType,
    RiskCategory,
    RiskSeverity,
    RuleClassification,
    ScaleEvaluation,
    StaleState,
    ThinFeatureResult,
    WallThicknessResult,
)
from .advanced_preparation_models import (
    AdvancedPreparationResult,
    AdvancedScaleRecommendation,
    BatchPreparationResult,
    BatchPreparationState,
    BridgeRiskRegion,
    BridgeRiskResult,
    ComposedProcessContext,
    DashboardSummary,
    FeatureFlagSet,
    HardwareProfile,
    MaterialFamily,
    MaterialProfile,
    MaterialProfileSnapshot,
    OrientationComparison,
    PerformanceLimit,
    PrintabilityBaselineRecord,
    ProcessContextSnapshot,
    RegressionComparison,
    RegressionState,
    ResinAdvisoryResult,
    ScaleInterval,
    SupportRiskReason,
    SupportRiskRegion,
    SupportRiskResult,
)

__all__ = (
    "AnalysisProfile",
    "AnalysisResult",
    "AnalysisSettingsSnapshot",
    "AnalysisSeverity",
    "BuildVolumeFitState",
    "BuildVolumeMetrics",
    "CheckConfidence",
    "CheckResult",
    "CheckTiming",
    "ContainmentEvidence",
    "DeepDiagnosticMetrics",
    "DimensionMetrics",
    "EdgeManifoldState",
    "EvaluationStatus",
    "GeometryMetrics",
    "IssueCategory",
    "IssueDomain",
    "IssueEvidence",
    "NormalConsistencyState",
    "ObjectMetadata",
    "PrinterProfile",
    "SelfIntersectionState",
    "ShellContainmentState",
    "ShellMetrics",
    "ShellOrientationState",
    "SurfaceVolumeMetrics",
    "TopologyMetrics",
    "TopologySignature",
    "TransformMetrics",
    "VertexManifoldState",
    "WatertightState",
    "RepairCandidate",
    "RepairAudit",
    "RepairCandidateType",
    "RepairCheckpointRecord",
    "RepairComparison",
    "RepairConfidence",
    "RepairDecision",
    "RepairOperationRecord",
    "RepairOperationStatus",
    "RepairOperationType",
    "RepairPlan",
    "RepairPlanItem",
    "RepairPlanStatus",
    "RepairSession",
    "RepairSessionStatus",
    "RepairSettingsSnapshot",
    "BuildPlateContactResult",
    "ContactClassification",
    "EvidenceState",
    "FloatingComponentResult",
    "OrientationCandidate",
    "OrientationResult",
    "PrintabilityConfidence",
    "PrintabilityGeometryFacts",
    "PrintabilityMode",
    "PrintabilityPrinterProfile",
    "PrintabilityReport",
    "PrintabilityResult",
    "PrintabilityRiskItem",
    "PrintabilityScore",
    "PrintabilitySettingsSnapshot",
    "PrintabilityStatus",
    "PrinterProfileSnapshot",
    "ProcessType",
    "RiskCategory",
    "RiskSeverity",
    "RuleClassification",
    "ScaleEvaluation",
    "StaleState",
    "ThinFeatureResult",
    "WallThicknessResult",
    "AdvancedPreparationResult",
    "AdvancedScaleRecommendation",
    "BatchPreparationResult",
    "BatchPreparationState",
    "BridgeRiskRegion",
    "BridgeRiskResult",
    "ComposedProcessContext",
    "DashboardSummary",
    "FeatureFlagSet",
    "HardwareProfile",
    "MaterialFamily",
    "MaterialProfile",
    "MaterialProfileSnapshot",
    "OrientationComparison",
    "PerformanceLimit",
    "PrintabilityBaselineRecord",
    "ProcessContextSnapshot",
    "RegressionComparison",
    "RegressionState",
    "ResinAdvisoryResult",
    "ScaleInterval",
    "SupportRiskReason",
    "SupportRiskRegion",
    "SupportRiskResult",
)

from .optimization_models import (
    AcceptanceRecord, CandidateEvaluation, CandidateGeometryOperation, CandidateTransform, ComparisonClassification,
    DiscardRecord, FidelityStatus, ObjectiveDelta, ObjectiveSnapshot, ObjectiveWeight, OptimizationAudit,
    OptimizationCandidate, OptimizationCheckpoint, OptimizationComparison, OptimizationConfidence, OptimizationOperationRecord,
    OptimizationOperationState, OptimizationOperationType, OptimizationObjective, OptimizationPlan, OptimizationPlanStep,
    OptimizationPolicy, OptimizationPolicySnapshot, OptimizationSession, OptimizationSessionState, RiskDelta,
)

__all__ += (
    "AcceptanceRecord", "CandidateEvaluation", "CandidateGeometryOperation", "CandidateTransform", "ComparisonClassification",
    "DiscardRecord", "FidelityStatus", "ObjectiveDelta", "ObjectiveSnapshot", "ObjectiveWeight", "OptimizationAudit",
    "OptimizationCandidate", "OptimizationCheckpoint", "OptimizationComparison", "OptimizationConfidence", "OptimizationOperationRecord",
    "OptimizationOperationState", "OptimizationOperationType", "OptimizationObjective", "OptimizationPlan", "OptimizationPlanStep",
    "OptimizationPolicy", "OptimizationPolicySnapshot", "OptimizationSession", "OptimizationSessionState", "RiskDelta",
)

from .intelligent_optimization_models import (
    ConstraintEvaluation, ConstraintKind, ConstraintSet, ConstraintSeverity, ConstraintState, DeterministicModel,
    DominanceRecord, DominanceState, EvidenceState as IntelligentEvidenceState, IntelligentOptimizationAudit,
    IntelligentOptimizationSession, IntelligentSessionState, IntelligentStrategy, ObjectiveDirection, ObjectiveMetric,
    ObjectiveVector, OptimizationConstraint, OptimizationOperationType as IntelligentOptimizationOperationType, ParetoFrontier, ParetoPoint,
    PruningRecord, RankingMethod, RankingRecord, RecommendationRecord, SearchBudget, SearchBudgetUsage, SearchMode,
    SearchPolicy, StrategyEvaluation, StrategyExplanation, StrategyGenerationReason, StrategyHistory,
    StrategyHistoryEntry, StrategySet, StrategyState, StrategyStep,
)

__all__ += (
    "ConstraintEvaluation", "ConstraintKind", "ConstraintSet", "ConstraintSeverity", "ConstraintState", "DeterministicModel",
    "DominanceRecord", "DominanceState", "IntelligentEvidenceState", "IntelligentOptimizationAudit", "IntelligentOptimizationSession",
    "IntelligentSessionState", "IntelligentStrategy", "ObjectiveDirection", "ObjectiveMetric", "ObjectiveVector", "OptimizationConstraint",
    "IntelligentOptimizationOperationType", "ParetoFrontier", "ParetoPoint", "PruningRecord", "RankingMethod", "RankingRecord",
    "RecommendationRecord", "SearchBudget", "SearchBudgetUsage", "SearchMode", "SearchPolicy", "StrategyEvaluation",
    "StrategyExplanation", "StrategyGenerationReason", "StrategyHistory", "StrategyHistoryEntry", "StrategySet", "StrategyState",
    "StrategyStep",
)
